package Ficha14.Escola.Enum;

public enum Curso {
    SOFTWARE_DEVELOPER,
    WEBSITES_ECOMMERCE,
    UX_UI_DESIGN,
    ANIMACAO_3D,
    CIENCIA_DADOS,
    JAVA_DEV,
    LINUX_ADMIN,
    SEGURANCA_INFORMACAO,
    MARKETING_DIGITAL,
    EXCEL_DASHBOARDS,
    ESTATISTICA_DADOS,
    WEBSITES_NO_CODE,
    ESCRITA_CREATIVA
}
